
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 04 23:29:46 EST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A3Symbol {
  /* terminals */
  public static final int TIMES = 13;
  public static final int READ = 5;
  public static final int ELSE = 6;
  public static final int PLUS = 11;
  public static final int INT = 23;
  public static final int RPAREN = 16;
  public static final int EQUAL = 20;
  public static final int SEMI = 17;
  public static final int END = 8;
  public static final int RETURN = 2;
  public static final int IF = 4;
  public static final int LPAREN = 15;
  public static final int WRITE = 3;
  public static final int ID = 10;
  public static final int NUM = 19;
  public static final int BEGIN = 7;
  public static final int STRING = 25;
  public static final int COMMA = 26;
  public static final int NEQUAL = 21;
  public static final int EOF = 0;
  public static final int DIVIDE = 14;
  public static final int MAIN = 9;
  public static final int MINUS = 12;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int QSTRING = 18;
  public static final int REAL = 24;
}

